kind: Service
apiVersion: v1
metadata:
  name: dra-crud-postgres
  labels:
    name: dra-crud-postgres
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 7788
      protocol: TCP
  selector:
    app: dra-crud-postgres
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dra-crud-postgres
spec:
  selector:
    matchLabels:
      app: dra-crud-postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: dra-crud-postgres
    spec:
      containers:
        - name: dra-crud-postgres
          image: pajicit2017/dra_crud_postgres:2.1
          ports:
            - containerPort: 7788
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
